# Tarea 10

### Kenneth Yar

In [2]:
%load_ext autoreload
import numpy as np
from src import descomposicion_LU, resolver_LU

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Ejercicio 1

a

In [3]:
%autoreload 2
A = np.array([[2,-3],[3,-1]])
B = np.array([[1,5],[2,0]])
C = np.matmul(A,B)
print("El resultado de la multiplicación es: \n",C)

El resultado de la multiplicación es: 
 [[-4 10]
 [ 1 15]]


b

In [4]:
%autoreload 2
A = np.array([[2,-3],[3,-1]])
B = np.array([[1,5,-4],[-3,2,0]])
C = np.matmul(A,B)
print("El resultado de la multiplicación es: \n",C)

El resultado de la multiplicación es: 
 [[ 11   4  -8]
 [  6  13 -12]]


c

In [5]:
%autoreload 2
A = np.array([[2,-3,1],[4,3,0],[5,2,-4]])
B = np.array([[0,1,-2],[1,0,-1],[2,3,-2]])
C = np.matmul(A,B)
print("El resultado de la multiplicación es: \n",C)

El resultado de la multiplicación es: 
 [[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


d

In [6]:
%autoreload 2
A = np.array([[2,1,2],[-2,3,0],[2,-1,3]])
B = np.array([[1,-2],[-4,1],[0,2]])
C = np.matmul(A,B)
print("El resultado de la multiplicación es: \n",C)

El resultado de la multiplicación es: 
 [[ -2   1]
 [-14   7]
 [  6   1]]


## Ejercicio 2

a

In [11]:
%autoreload 2
A = np.array([[4,2,6],[3,0,7],[-2,-1,-3]])
det = np.linalg.det(A)
if(det==0):
    print("El determinante es:",det, "\nAsí que, la matriz es singular y no posee inversa")
else:
    inv = np.linalg.inv(A)
    print("El determinante es:",det, "\nSu matriz inversa es:\n", inv)

El determinante es: 0.0 
Así que, la matriz es singular y no posee inversa


b

In [12]:
%autoreload 2
A = np.array([[1,2,0],[2,1,-1],[3,1,1]])
det = np.linalg.det(A)
if(det==0):
    print("El determinante es:",det, "\nAsí que, la matriz es singular y no posee inversa")
else:
    inv = np.linalg.inv(A)
    print("El determinante es:",det, "\nSu matriz inversa es:\n", inv)

El determinante es: -8.000000000000002 
Su matriz inversa es:
 [[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]


c

In [13]:
%autoreload 2
A = np.array([[1,1,-1,1],[1,2,-4,-2],[2,1,1,5],[-1,0,-2,-4]])
det = np.linalg.det(A)
if(det==0):
    print("El determinante es:",det, "\nAsí que, la matriz es singular y no posee inversa")
else:
    inv = np.linalg.inv(A)
    print("El determinante es:",det, "\nSu matriz inversa es:\n", inv)

El determinante es: 0.0 
Así que, la matriz es singular y no posee inversa


d

In [14]:
%autoreload 2
A = np.array([[4,0,0,0],[6,7,0,0],[9,11,1,0],[5,4,1,1]])
det = np.linalg.det(A)
if(det==0):
    print("El determinante es:",det, "\nAsí que, la matriz es singular y no posee inversa")
else:
    inv = np.linalg.inv(A)
    print("El determinante es:",det, "\nSu matriz inversa es:\n", inv)

El determinante es: 28.00000000000001 
Su matriz inversa es:
 [[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]


## Ejercicio 3