# Tarea 10

Repositorio: https://github.com/KennethJYS/Tarea-10-Descomposici-n-LU

### Kenneth Yar

In [2]:
%load_ext autoreload
import numpy as np
from src import descomposicion_LU, resolver_LU

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Ejercicio 1

a

In [3]:
%autoreload 2
A = np.array([[2,-3],[3,-1]])
B = np.array([[1,5],[2,0]])
C = np.matmul(A,B)
print("El resultado de la multiplicación es: \n",C)

El resultado de la multiplicación es: 
 [[-4 10]
 [ 1 15]]


b

In [4]:
%autoreload 2
A = np.array([[2,-3],[3,-1]])
B = np.array([[1,5,-4],[-3,2,0]])
C = np.matmul(A,B)
print("El resultado de la multiplicación es: \n",C)

El resultado de la multiplicación es: 
 [[ 11   4  -8]
 [  6  13 -12]]


c

In [5]:
%autoreload 2
A = np.array([[2,-3,1],[4,3,0],[5,2,-4]])
B = np.array([[0,1,-2],[1,0,-1],[2,3,-2]])
C = np.matmul(A,B)
print("El resultado de la multiplicación es: \n",C)

El resultado de la multiplicación es: 
 [[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


d

In [6]:
%autoreload 2
A = np.array([[2,1,2],[-2,3,0],[2,-1,3]])
B = np.array([[1,-2],[-4,1],[0,2]])
C = np.matmul(A,B)
print("El resultado de la multiplicación es: \n",C)

El resultado de la multiplicación es: 
 [[ -2   1]
 [-14   7]
 [  6   1]]


## Ejercicio 2

a

In [11]:
%autoreload 2
A = np.array([[4,2,6],[3,0,7],[-2,-1,-3]])
det = np.linalg.det(A)
if(det==0):
    print("El determinante es:",det, "\nAsí que, la matriz es singular y no posee inversa")
else:
    inv = np.linalg.inv(A)
    print("El determinante es:",det, "\nSu matriz inversa es:\n", inv)

El determinante es: 0.0 
Así que, la matriz es singular y no posee inversa


b

In [12]:
%autoreload 2
A = np.array([[1,2,0],[2,1,-1],[3,1,1]])
det = np.linalg.det(A)
if(det==0):
    print("El determinante es:",det, "\nAsí que, la matriz es singular y no posee inversa")
else:
    inv = np.linalg.inv(A)
    print("El determinante es:",det, "\nSu matriz inversa es:\n", inv)

El determinante es: -8.000000000000002 
Su matriz inversa es:
 [[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]


c

In [13]:
%autoreload 2
A = np.array([[1,1,-1,1],[1,2,-4,-2],[2,1,1,5],[-1,0,-2,-4]])
det = np.linalg.det(A)
if(det==0):
    print("El determinante es:",det, "\nAsí que, la matriz es singular y no posee inversa")
else:
    inv = np.linalg.inv(A)
    print("El determinante es:",det, "\nSu matriz inversa es:\n", inv)

El determinante es: 0.0 
Así que, la matriz es singular y no posee inversa


d

In [14]:
%autoreload 2
A = np.array([[4,0,0,0],[6,7,0,0],[9,11,1,0],[5,4,1,1]])
det = np.linalg.det(A)
if(det==0):
    print("El determinante es:",det, "\nAsí que, la matriz es singular y no posee inversa")
else:
    inv = np.linalg.inv(A)
    print("El determinante es:",det, "\nSu matriz inversa es:\n", inv)

El determinante es: 28.00000000000001 
Su matriz inversa es:
 [[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]


## Ejercicio 3

Ya que ambos sistemas poseen la misma matriz de coeficientes:

In [15]:
%autoreload 2
A = [[1,-1,2,-1],[1,0,-1,1],[2,1,3,-4],[0,-1,1,-1]]
L,U = descomposicion_LU(A)
print("Matriz L:\n",L)
print("Matriz U:\n",U)

[02-04 21:51:11][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  3. -1. -2.]
 [ 0. -1.  1. -1.]]
[02-04 21:51:11][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0. -2.  1.]]
[02-04 21:51:11][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[02-04 21:51:11][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
Matriz L:
 [[ 1.    0.    0.    0.  ]
 [ 1.    1.    0.    0.  ]
 [ 2.    3.    1.    0.  ]
 [ 0.   -1.   -0.25  1.  ]]
Matriz U:
 [[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]


In [16]:
%autoreload 2
b_1 = [6,4,-2,5]
sol_1 = resolver_LU(L,U,b_1)

[02-04 21:51:49][INFO] Sustitución hacia adelante
[02-04 21:51:49][INFO] y = 
[[ 6.]
 [-2.]
 [-8.]
 [ 1.]]
[02-04 21:51:49][INFO] Sustitución hacia atrás
[02-04 21:51:49][INFO] i = 2
[02-04 21:51:49][INFO] suma = [8.]
[02-04 21:51:49][INFO] U[i, i] = 8.0
[02-04 21:51:49][INFO] y[i] = [-8.]
[02-04 21:51:49][INFO] i = 1
[02-04 21:51:49][INFO] suma = [4.]
[02-04 21:51:49][INFO] U[i, i] = 1.0
[02-04 21:51:49][INFO] y[i] = [-2.]
[02-04 21:51:49][INFO] i = 0
[02-04 21:51:49][INFO] suma = [3.]
[02-04 21:51:49][INFO] U[i, i] = 1.0
[02-04 21:51:49][INFO] y[i] = [6.]


In [17]:
%autoreload 2
b_2 = [1,1,2,-1]
sol_2 = resolver_LU(L,U,b_2)

[02-04 21:52:17][INFO] Sustitución hacia adelante
[02-04 21:52:17][INFO] y = 
[[ 1.]
 [ 0.]
 [ 0.]
 [-1.]]
[02-04 21:52:17][INFO] Sustitución hacia atrás
[02-04 21:52:17][INFO] i = 2
[02-04 21:52:17][INFO] suma = [-8.]
[02-04 21:52:17][INFO] U[i, i] = 8.0
[02-04 21:52:17][INFO] y[i] = [0.]
[02-04 21:52:17][INFO] i = 1
[02-04 21:52:17][INFO] suma = [-1.]
[02-04 21:52:17][INFO] U[i, i] = 1.0
[02-04 21:52:17][INFO] y[i] = [0.]
[02-04 21:52:17][INFO] i = 0
[02-04 21:52:17][INFO] suma = [0.]
[02-04 21:52:17][INFO] U[i, i] = 1.0
[02-04 21:52:17][INFO] y[i] = [1.]


## Ejercicio 4

## Ejercicio 5

a

In [18]:
%autoreload 2
L = np.array([[1,0,0],[2,1,0],[-1,0,1]])
U = np.array([[2,3,-1],[0,-2,1],[0,0,3]])
b = [2,-1,1]
resolver_LU(L,U,b)

[02-04 22:36:15][INFO] Sustitución hacia adelante
[02-04 22:36:15][INFO] y = 
[[ 2.]
 [-5.]
 [ 3.]]
[02-04 22:36:15][INFO] Sustitución hacia atrás
[02-04 22:36:15][INFO] i = 1
[02-04 22:36:15][INFO] suma = [1.]
[02-04 22:36:15][INFO] U[i, i] = -2
[02-04 22:36:15][INFO] y[i] = [-5.]
[02-04 22:36:15][INFO] i = 0
[02-04 22:36:15][INFO] suma = [8.]
[02-04 22:36:15][INFO] U[i, i] = 2
[02-04 22:36:15][INFO] y[i] = [2.]


array([[-3.],
       [ 3.],
       [ 1.]])

b

In [19]:
%autoreload 2
L = np.array([[2,0,0],[-1,1,0],[3,2,-1]])
U = np.array([[1,1,1],[0,1,2],[0,0,1]])
b = [-1,3,0]
resolver_LU(L,U,b)

[02-04 22:38:18][INFO] Sustitución hacia adelante
[02-04 22:38:18][INFO] y = 
[[-0.5]
 [ 2.5]
 [ 3.5]]
[02-04 22:38:18][INFO] Sustitución hacia atrás
[02-04 22:38:18][INFO] i = 1
[02-04 22:38:18][INFO] suma = [7.]
[02-04 22:38:18][INFO] U[i, i] = 1
[02-04 22:38:18][INFO] y[i] = [2.5]
[02-04 22:38:18][INFO] i = 0
[02-04 22:38:18][INFO] suma = [-1.]
[02-04 22:38:18][INFO] U[i, i] = 1
[02-04 22:38:18][INFO] y[i] = [-0.5]


array([[ 0.5],
       [-4.5],
       [ 3.5]])

## Ejercicio 6

a

In [20]:
%autoreload 2
A = [[2,-1,1],[3,3,9],[3,3,5]]
L,U = descomposicion_LU(A)
print("Matriz L:\n",L)
print("Matriz U:\n",U)

[02-04 22:38:58][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   4.5  3.5]]
[02-04 22:38:58][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
[02-04 22:38:58][INFO] 
[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]
Matriz L:
 [[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]
Matriz U:
 [[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]


b

In [21]:
%autoreload 2
B = [[1.012,-2.132,3.104],[-2.132,4.096,-7.013],[3.104,-7.013,0.014]]
L,U = descomposicion_LU(B)
print("Matriz L:\n",L)
print("Matriz U:\n",U)

[02-04 22:39:27][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]
[02-04 22:39:27][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
[02-04 22:39:27][INFO] 
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
Matriz L:
 [[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]
Matriz U:
 [[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]


c

In [22]:
%autoreload 2
C = [[2,0,0,0],[1,1.5,0,0],[0,-3,0.5,0],[2,-2,1,1]]
L,U = descomposicion_LU(C)
print("Matriz L:\n",L)
print("Matriz U:\n",U)

[02-04 22:39:54][INFO] 
[[ 2.   0.   0.   0. ]
 [ 0.   1.5  0.   0. ]
 [ 0.  -3.   0.5  0. ]
 [ 0.  -2.   1.   1. ]]
[02-04 22:39:54][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  1.  1. ]]
[02-04 22:39:54][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]
[02-04 22:39:54][INFO] 
[[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]
Matriz L:
 [[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -2.          1.          0.        ]
 [ 1.         -1.33333333  2.          1.        ]]
Matriz U:
 [[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]


d

In [23]:
%autoreload 2
D = [[2.1756,4.0231,-2.1732,5.1967],[-4.0231,6.0000,0,1.1973],
     [-1.0000,-5.2107,1.1111,0],[6.0235,7.0000,0,-4.1561]]
L,U = descomposicion_LU(D)
print("Matriz L:\n",L)
print("Matriz U:\n",U)

[02-04 22:40:28][INFO] 
[[  2.1756       4.0231      -2.1732       5.1967    ]
 [  0.          13.43948042  -4.01866194  10.80699101]
 [  0.          -3.36150897   0.11220314   2.38862842]
 [  0.          -4.13860216   6.01685521 -18.54400331]]
[02-04 22:40:28][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.09169403e+00]
 [ 0.00000000e+00  0.00000000e+00  4.77933394e+00 -1.52160595e+01]]
[02-04 22:40:28][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.09169403e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.20361280e+01]]
[02-04 22:40:28][INFO] 
[[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.000000

## Ejercicio 7

a